### ISSUE TITLE
Feature request: SARIF format support

### ISSUE THREAD

**Issue by rbut-husaim-gte** [microsoft/infersharpaction#42]
Hello dear community,

It seems that at the moment the format of the output for the github action is hard-coded and it is `txt`. It will be more valuable to support SARIF option as well as this is the main format for GitHub Security Center support. 

As far as I can see [both infer](https://github.com/xi-liu-ds/infer/blob/fe9ea0ff4c90264b3eb55cad3e712f4f9419a5c3/infer/man/man1/infer-full.txt#L1211) and [infer#](https://github.com/microsoft/infersharp/blob/main/run_infersharp.sh#L34) support this as an option however it is no exposed as part of this action. It could be for sure added to this [script](https://github.com/microsoft/infersharp/blob/main/run_infersharp_ci.sh) that is used under the hood of the action.

I would propose this feature to be added to the GitHub action as it will bring a lot of value to the consumers.

Thanks.

**Comment by xinshiMSFT** [comment]
Yes! Will update this. Thank you!

**Comment by xinshiMSFT** [comment]
[v1.2.1 now supports SARIF](https://github.com/marketplace/actions/infersharp?version=v1.2.1). Thank you for the feedback!

**Comment by rbut-husaim-gte** [comment]
Hello @xinshiMSFT ,
I've checked it on one of the projects and it works.
Thank you.
