### ISSUE TITLE
This is a more significant change, as the `[]` operator of `std::span` is not considered safe anymore (unlike `gsl::span` it doesn't fail-fast). When fixing it with `til::at` I noticed that `for_each` can be simplified with a for-range loop.

### ISSUE THREAD

**Issue by RasstAdonai** [microsoft/infersharpaction#52]
This is a more significant change, as the `[]` operator of `std::span` is not considered safe anymore (unlike `gsl::span` it doesn't fail-fast). When fixing it with `til::at` I noticed that `for_each` can be simplified with a for-range loop.

_Originally posted by @lhecker in https://github.com/microsoft/terminal/pull/14763#discussion_r1092243111_

**Comment by matjin** [comment]
Is this comment/issue intentional?

**Comment by lhecker** [comment]
I'd be quite surprised if it was. I believe it's either an accident or spam and can be closed, given that it's a literal copy of one of my comments from an entirely unrelated project in C++.
